name: Build Android APK
on:
  workflow_dispatch: # Permette di lanciare la compilazione manualmente con un click

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true" # Silenzia l'avviso e aggiorna i sistemi a Node 24

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Configurazione Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Configurazione Java (Necessario per compilare Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Installa dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

          # Risolve un potenziale problema di permessi del compilatore su Linux
          pip install "flet[all]" 

      - name: Fabbrica il file config.py usando i Secrets
        run: |
          echo "SUPABASE_URL = '${{ secrets.SUPABASE_URL }}'" > src/config.py
          echo "SUPABASE_KEY = '${{ secrets.SUPABASE_KEY }}'" >> src/config.py

      - name: Compilazione APK con Flet
        run: |
          flet build apk src --no-analytics

      - name: Carica l'APK pronto nei download di GitHub
        uses: actions/upload-artifact@v4
        with:
          name: tokyo-travel-wallet-apk
          path: build/apk/*.apk
