name: Build Web App
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Setup Flet
        run: pip install flet
      
      - name: Crea requirements e config
        run: |
          # Diamo al builder solo flet, perché il resto è libreria standard
          echo "flet" > src/requirements.txt
          
          # Genera il file config.py con le tue credenziali
          echo "SUPABASE_URL = '${{ secrets.SUPABASE_URL }}'" > src/config.py
          echo "SUPABASE_KEY = '${{ secrets.SUPABASE_KEY }}'" >> src/config.py
      
      - name: Build Web
        run: flet build web src --output build_web
      
      - name: Carica artefatto
        uses: actions/upload-artifact@v4
        with:
          name: web-app
          path: build_web
          
